version: '3.7'

services:
  doc_service:
    build: ./crud_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./crud_service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://postgres:FGHyuhT56@docs_db/docs_db_dev
      - USER_SERVICE_HOST_URL=http://user_service:8000/api/v1/user/
    depends_on:
        - docs_db

  docs_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_doc:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=FGHyuhT56
      - POSTGRES_DB=docs_db_dev

  user_service:
    build: ./user_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./user_service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://postgres:FGHyuhT56@users_db/users_db_dev
    depends_on:
        - users_db

  users_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=FGHyuhT56
      - POSTGRES_DB=users_db_dev

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service
      - doc_service

volumes:
  postgres_data_doc:
  postgres_data_user: